from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path
from typing import TYPE_CHECKING, Any, Protocol, Sequence

if TYPE_CHECKING:
    from deepresearch_agent.premise import PremiseAssessment
    from deepresearch_agent.reporting import GroundedFactRenderer
    from deepresearch_agent.schemas import Evidence, ReportEvidenceSelection


class TableExtractors(Protocol):
    """Domain-owned parsing and merge policy for authoritative tables."""

    def authoritative_backfills(
        self,
        research_id: str,
        sub_question: Any,
        sources: list[Any],
        *,
        rejections: list[Any],
    ) -> list[Any]: ...

    def merge_authoritative_evidence(
        self, evidence: list[Any], backfills: list[Any]
    ) -> list[Any]: ...


class NumericCitationPolicy(Protocol):
    """Domain rules for checking numeric claims against cited evidence."""

    def has_numeric_mismatch(
        self,
        claim_text: str,
        cited_evidence: Sequence[Any],
        *,
        required_metrics: set[str] | None = None,
    ) -> bool: ...

    def is_main_business_margin_dimension(self, dimension: str | None) -> bool: ...


class PlanningDomain(Protocol):
    def deterministic_plan(self, topic: str, depth_level: int) -> Any | None: ...
    def propagate_plan_identity(self, plan: Any, topic: str) -> Any: ...
    def valid_structured_request(self, request: Any) -> bool: ...


class DisclosureQueryDomain(Protocol):
    def primary_source_keyword(self, *, financial_intent: bool) -> str: ...
    def primary_source_terms(self, *, financial_intent: bool) -> tuple[str, ...]: ...


class NumericCheckingDomain(Protocol):
    def metric_table_path(self) -> Path: ...
    def numeric_consistency_checker(
        self,
        metric_table: dict[str, Any],
        *,
        relative_tolerance: float,
        absolute_tolerance: float,
    ) -> Any: ...
    def is_historical_annual_disclosure(self, evidence: Any) -> bool: ...
    def is_legal_disclaimer_template(self, evidence: Any) -> bool: ...


class StructuredDataDomain(Protocol):
    def canonical_metric(self, value: str | None) -> str: ...
    def structured_metric_aliases(self) -> Mapping[str, str]: ...
    def fixture_metric_aliases(self) -> Mapping[str, str]: ...
    def default_structured_metrics(self) -> tuple[str, ...]: ...
    def structured_metric_unit(self, metric_name: str) -> str | None: ...
    def equity_exchange_label(self) -> str: ...
    #: `(endpoint, code_column, name_column)` per listing venue. Which venues
    #: exist and what their columns are called is market knowledge, so the
    #: shared symbol-table cache takes it from here rather than hardcoding it.
    def equity_listing_sources(self) -> tuple[tuple[str, str, str], ...]: ...
    def structured_issuer_aliases(self) -> Mapping[str, str]: ...
    def structured_xbrl_concepts(self) -> Mapping[str, tuple[str, ...]]: ...
    def unsupported_xbrl_metrics(self) -> tuple[str, ...]: ...


class MetricCoverageDomain(Protocol):
    def canonical_metric(self, value: str | None) -> str: ...
    def parse_period(self, value: str | None) -> str | None: ...
    def evidence_matches_metric(self, evidence: Any, required_metric: str) -> bool: ...
    def comparison_observed(self, evidence: Any) -> bool: ...


class ReportingDomain(MetricCoverageDomain, Protocol):
    def assess_premise(
        self,
        topic: str,
        evidence: list[Evidence],
        selections: list[ReportEvidenceSelection],
    ) -> PremiseAssessment: ...
    def line_adopts_contradicted_premise(
        self, line: str, assessment: PremiseAssessment
    ) -> bool: ...
    def metric_table_path(self) -> Path: ...
    def metric_claim_pattern(self) -> Any: ...
    def numeric_citation_policy(self) -> NumericCitationPolicy: ...
    def reader_derived_metrics(self, evidence: list[Any]) -> list[dict[str, Any]]: ...
    def reader_risk_visible(self, line: str) -> bool: ...
    def reader_assumption_visible(self, line: str) -> bool: ...
    def reader_metric_gap_explanation(
        self, metric: str, derived_periods: Sequence[str] = ()
    ) -> str: ...
    #: Which requested metrics were computed from components, and for which
    #: periods. A gap notice that does not know this contradicts the derived
    #: value printed below it.
    def derived_metric_periods(self, evidence: list[Any]) -> Mapping[str, tuple[str, ...]]: ...
    #: Which of ``required`` a sentence talks about, by the domain's own
    #: vocabulary. The renderer needs a topicality signal that does not depend on
    #: two claims citing the same evidence id, because that signal is absent
    #: exactly when the reader's key findings are gap notices.
    def metrics_mentioned(self, text: str, required: set[str]) -> set[str]: ...
    #: What makes two cited amounts the same published figure. The coverage
    #: section renders one item per key, so the domain -- not the reporter --
    #: decides whether a restatement in another scale is a second figure.
    def coverage_figure_key(self, evidence: Any) -> tuple[str, str]: ...


class TableExtractionDomain(Protocol):
    def table_extractors(self) -> TableExtractors: ...


class DisclosureTitleDomain(Protocol):
    def report_year_from_title(self, title: str) -> int | None: ...
    def is_full_annual_report_query(self, keyword: str) -> bool: ...
    def is_full_annual_report_title(self, title: str) -> bool: ...


class SkillSelectionDomain(Protocol):
    def metric_skill_applicable(self, metadata: Any, context: str) -> bool: ...


@dataclass(frozen=True)
class RetrievalFilterValues:
    """Domain-owned values for the generic retrieval filter contract."""

    doc_types: tuple[str, ...] = ()
    entity_ids: tuple[str, ...] = ()
    period_labels: tuple[str, ...] = ()
    preferred_period_labels: tuple[str, ...] = ()


class RetrievalDomain(Protocol):
    """Translate a domain query into neutral retrieval-filter values."""

    def retrieval_filter_values(self, query: str) -> RetrievalFilterValues: ...

    def expand_retrieval_query(self, query: str) -> str: ...


class WebSourceGovernanceDomain(Protocol):
    """Domain-owned rejection policy for reader-visible web sources."""

    def web_source_rejection_reason(
        self,
        source: Any,
        target_periods: tuple[str, ...],
    ) -> str | None: ...


class DomainPack(Protocol):
    """Explicit domain boundary used by generic orchestration code."""

    name: str

    def canonical_metric(self, value: str | None) -> str: ...

    def parse_period(self, value: str | None) -> str | None: ...

    def amount_units(self) -> Mapping[str, Decimal]: ...

    def structured_metric_aliases(self) -> Mapping[str, str]: ...

    def fixture_metric_aliases(self) -> Mapping[str, str]: ...

    def default_structured_metrics(self) -> tuple[str, ...]: ...

    def structured_metric_unit(self, metric_name: str) -> str | None: ...

    def equity_exchange_label(self) -> str: ...

    def structured_issuer_aliases(self) -> Mapping[str, str]: ...

    def structured_xbrl_concepts(self) -> Mapping[str, tuple[str, ...]]: ...

    def unsupported_xbrl_metrics(self) -> tuple[str, ...]: ...

    def financial_intent_terms(self) -> tuple[str, ...]: ...

    def primary_source_keyword(self, *, financial_intent: bool) -> str: ...

    def primary_source_terms(self, *, financial_intent: bool) -> tuple[str, ...]: ...

    def grounded_fact_renderer(self) -> GroundedFactRenderer: ...

    def table_extractors(self) -> TableExtractors: ...

    def metric_table_path(self) -> Path: ...

    def metric_claim_pattern(self) -> Any: ...

    def comparison_observed(self, evidence: Any) -> bool: ...

    def evidence_matches_metric(self, evidence: Any, required_metric: str) -> bool: ...

    def demo_numeric_claim(self, claims: list[Any]) -> Any | None: ...

    def demo_scope_claim(
        self, claims: list[Any], numeric_change: Any | None
    ) -> Any | None: ...

    def scope_change_summary(self, label: str) -> str: ...

    def is_full_annual_report_query(self, keyword: str) -> bool: ...

    def is_full_annual_report_title(self, title: str) -> bool: ...

    def report_year_from_title(self, title: str) -> int | None: ...

    def is_amount_unit(self, value: str) -> bool: ...

    def golden_type_distribution(self) -> Mapping[str, int]: ...

    def evidence_explains_change(self, text: str) -> bool: ...

    def document_type_tokens(self) -> tuple[str, ...]: ...

    def document_type_for_direction(self, direction: str) -> str: ...

    def metric_gap_direction(self) -> str: ...

    def evidence_gap_direction(self) -> str: ...

    def metric_skill_applicable(self, metadata: Any, context: str) -> bool: ...

    def numeric_consistency_checker(
        self,
        metric_table: dict[str, Any],
        *,
        relative_tolerance: float,
        absolute_tolerance: float,
    ) -> Any: ...

    def numeric_citation_policy(self) -> NumericCitationPolicy: ...

    def deterministic_plan(self, topic: str, depth_level: int) -> Any | None: ...

    def propagate_plan_identity(self, plan: Any, topic: str) -> Any: ...

    def valid_structured_request(self, request: Any) -> bool: ...

    def retrieval_filter_values(self, query: str) -> RetrievalFilterValues: ...

    def expand_retrieval_query(self, query: str) -> str: ...

    def web_source_rejection_reason(
        self,
        source: Any,
        target_periods: tuple[str, ...],
    ) -> str | None: ...
