from __future__ import annotations

from collections.abc import Mapping
from decimal import Decimal
from pathlib import Path
from typing import TYPE_CHECKING, Any, Protocol, Sequence

if TYPE_CHECKING:
    from deepresearch_agent.reporting import GroundedFactRenderer


class TableExtractors(Protocol):
    """Domain-owned parsing and merge policy for authoritative tables."""

    def authoritative_backfills(
        self,
        research_id: str,
        sub_question: Any,
        sources: list[Any],
        *,
        rejections: list[Any],
    ) -> list[Any]: ...

    def merge_authoritative_evidence(
        self, evidence: list[Any], backfills: list[Any]
    ) -> list[Any]: ...


class NumericCitationPolicy(Protocol):
    """Domain rules for checking numeric claims against cited evidence."""

    def has_numeric_mismatch(
        self,
        claim_text: str,
        cited_evidence: Sequence[Any],
        *,
        required_metrics: set[str] | None = None,
    ) -> bool: ...

    def is_main_business_margin_dimension(self, dimension: str | None) -> bool: ...


class PlanningDomain(Protocol):
    def deterministic_plan(self, topic: str, depth_level: int) -> Any | None: ...
    def propagate_plan_identity(self, plan: Any, topic: str) -> Any: ...
    def valid_structured_request(self, request: Any) -> bool: ...


class DisclosureQueryDomain(Protocol):
    def primary_source_keyword(self, *, financial_intent: bool) -> str: ...
    def primary_source_terms(self, *, financial_intent: bool) -> tuple[str, ...]: ...


class NumericCheckingDomain(Protocol):
    def metric_table_path(self) -> Path: ...
    def numeric_consistency_checker(
        self,
        metric_table: dict[str, Any],
        *,
        relative_tolerance: float,
        absolute_tolerance: float,
    ) -> Any: ...


class StructuredDataDomain(Protocol):
    def structured_metric_aliases(self) -> Mapping[str, str]: ...
    def fixture_metric_aliases(self) -> Mapping[str, str]: ...
    def default_structured_metrics(self) -> tuple[str, ...]: ...
    def structured_metric_unit(self, metric_name: str) -> str | None: ...
    def equity_exchange_label(self) -> str: ...


class MetricCoverageDomain(Protocol):
    def canonical_metric(self, value: str | None) -> str: ...
    def parse_period(self, value: str | None) -> str | None: ...
    def evidence_matches_metric(self, evidence: Any, required_metric: str) -> bool: ...
    def comparison_observed(self, evidence: Any) -> bool: ...


class ReportingDomain(MetricCoverageDomain, Protocol):
    def metric_table_path(self) -> Path: ...
    def metric_claim_pattern(self) -> Any: ...
    def numeric_citation_policy(self) -> NumericCitationPolicy: ...


class TableExtractionDomain(Protocol):
    def table_extractors(self) -> TableExtractors: ...


class DisclosureTitleDomain(Protocol):
    def report_year_from_title(self, title: str) -> int | None: ...
    def is_full_annual_report_query(self, keyword: str) -> bool: ...
    def is_full_annual_report_title(self, title: str) -> bool: ...


class SkillSelectionDomain(Protocol):
    def metric_skill_applicable(self, metadata: Any, context: str) -> bool: ...


class DomainPack(Protocol):
    """Explicit domain boundary used by generic orchestration code."""

    name: str

    def canonical_metric(self, value: str | None) -> str: ...

    def parse_period(self, value: str | None) -> str | None: ...

    def amount_units(self) -> Mapping[str, Decimal]: ...

    def structured_metric_aliases(self) -> Mapping[str, str]: ...

    def fixture_metric_aliases(self) -> Mapping[str, str]: ...

    def default_structured_metrics(self) -> tuple[str, ...]: ...

    def structured_metric_unit(self, metric_name: str) -> str | None: ...

    def equity_exchange_label(self) -> str: ...

    def primary_source_keyword(self, *, financial_intent: bool) -> str: ...

    def primary_source_terms(self, *, financial_intent: bool) -> tuple[str, ...]: ...

    def grounded_fact_renderer(self) -> GroundedFactRenderer: ...

    def table_extractors(self) -> TableExtractors: ...

    def metric_table_path(self) -> Path: ...

    def metric_claim_pattern(self) -> Any: ...

    def comparison_observed(self, evidence: Any) -> bool: ...

    def evidence_matches_metric(self, evidence: Any, required_metric: str) -> bool: ...

    def demo_numeric_claim(self, claims: list[Any]) -> Any | None: ...

    def demo_scope_claim(
        self, claims: list[Any], numeric_change: Any | None
    ) -> Any | None: ...

    def scope_change_summary(self, label: str) -> str: ...

    def is_full_annual_report_query(self, keyword: str) -> bool: ...

    def is_full_annual_report_title(self, title: str) -> bool: ...

    def report_year_from_title(self, title: str) -> int | None: ...

    def is_amount_unit(self, value: str) -> bool: ...

    def golden_type_distribution(self) -> Mapping[str, int]: ...

    def evidence_explains_change(self, text: str) -> bool: ...

    def document_type_tokens(self) -> tuple[str, ...]: ...

    def document_type_for_direction(self, direction: str) -> str: ...

    def metric_gap_direction(self) -> str: ...

    def evidence_gap_direction(self) -> str: ...

    def metric_skill_applicable(self, metadata: Any, context: str) -> bool: ...

    def numeric_consistency_checker(
        self,
        metric_table: dict[str, Any],
        *,
        relative_tolerance: float,
        absolute_tolerance: float,
    ) -> Any: ...

    def numeric_citation_policy(self) -> NumericCitationPolicy: ...

    def deterministic_plan(self, topic: str, depth_level: int) -> Any | None: ...

    def propagate_plan_identity(self, plan: Any, topic: str) -> Any: ...

    def valid_structured_request(self, request: Any) -> bool: ...
